### ISSUE TITLE
Stopped combining audio and video a month ago on Mac.

### ISSUE THREAD

**Issue by d00d-0** [feller-prj/extractor-project#20]
I know ffmpeg is functional because I can combine using command line, but somehow the browser integration doesn't work.
This is the Firefox debug console output;
stderr output from native app com.add0n.node: (node:80653) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

**Comment by Verequus** [comment]
I have basically the same problem, but on windows. I find searching for com.add0n.node these messages:

> stderr output from native app com.add0n.node: events.js:160
stderr output from native app com.add0n.node:       throw er; // Unhandled 'error' event
stderr output from native app com.add0n.node:       ^
stderr output from native app com.add0n.node: 
stderr output from native app com.add0n.node: Error: spawn C:\Users\xxxx\Downloads ENOENT
stderr output from native app com.add0n.node:     at exports._errnoException (util.js:1018:11)
stderr output from native app com.add0n.node:     at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
stderr output from native app com.add0n.node:     at onErrorNT (internal/child_process.js:367:16)
stderr output from native app com.add0n.node:     at _combinedTickCallback (internal/process/next_tick.js:80:11)
stderr output from native app com.add0n.node:     at process._tickCallback (internal/process/next_tick.js:104:9)
